src/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.basic, name='basic'),
    path('calculate_price/', views.calculate_price, name='calculate_price'),
    path('add_order_element/', views.add_order_element, name='add_order_element'),
    path('add_book_element/', views.add_book_element, name='add_book_element'),
    # path('submit_form/', views.submit_form, name='submit_form'),
    path('submit_head_form/', views.submit_head_form, name='submit_head_form'),
    path('verify_upload_file/', views.verify_upload_file, name='verify_upload_file'),

]

src/pay/urls.py
from django.urls import path
from . import views

app_name = 'pay'
urlpatterns = [
    path('yandex_redirect/<int:head_orders_id>/', views.yandex_redirect, name='yandex_redirect'),
    path('error/', views.PayError.as_view(), name='error'),
    path('success/<slug:token>/', views.pay_success, name='success'),

]

src/wideprint_moscow/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name='base/robots.txt',content_type='text/plain')),
    path('sitemap.xml', TemplateView.as_view(template_name='base/sitemap.xml',content_type='application/xml')),
    path('admin/', admin.site.urls),
    path('auth/', include('users_app.urls', namespace='authorization')),
    path('test_auth/', include('auth_.urls', namespace='test_authorization')),
    path('', include('main.urls', namespace='main')),
    path('order_status/', include('order_status.urls', namespace='order_status')),
    path('pay/', include('pay.urls', namespace='pay')),
    path('', include('single_pages.urls', namespace='single_pages')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pay/models.py
from django.db import models

# Create your models here.

src/pay/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.urls import reverse
from main.models import HeadOrders

def yandex_redirect(request, **kwargs):
    if request.method == 'GET':
        order_id = kwargs.get('head_orders_id')
        order = HeadOrders.objects.get(id=order_id)
        context = {
            'order_id': order_id,
            'sum': order.total_price_of_orders,
            'success_token': order.success_token
        }
        return render(request, 'pay/yandex_redirect.html', context=context)


class PayError(TemplateView):
    template_name = "pay/pay_error.html"


def pay_success(request, **kwargs):
    if request.method == 'GET':
        token = kwargs.get('token')
        order = HeadOrders.objects.get(success_token=token)
        order.status = 'not_ready'
        user = User.objects.get(headorders__success_token=token)

        domain = request.build_absolute_uri('/')[:-1]
        unsubscribe_link = reverse('users_app:unsubscribe', kwargs={'token': user.userextend.unsubscribe_token})
        unsubscribe_url = '{domain}{path}'.format(domain=domain, path=unsubscribe_link)

        mail_for_send = EmailMessage(
            'Заказ успешно оплачен',
            body='Ваш заказ №{} принят в работу, ожидайте звонка оператора.'.format(order.id),
            from_email='wideprintmoscow@gmail.com',
            to=[user.email],
            headers={'Precedence': 'bulk', 'List-Unsubscribe': unsubscribe_url},

        )
        mail_for_send.send(fail_silently=False)
        order.save()
        return render(request, 'pay/pay_success.html')

src/pay/templates/pay/pay_error.html
{% extends 'base/base.html' %}
{% load staticfiles %}
    {% load mathfilters %}
    {% block title %}Широкоформатная печать Москва{% endblock title %}
{% block content %}
    <h1>Во время оплаты произошла ошибка</h1>
{% endblock content %}

src/pay/templates/pay/pay_success.html
{% extends 'base/base.html' %}
{% load staticfiles %}
    {% load mathfilters %}
    {% block title %}Широкоформатная печать Москва{% endblock title %}
{% block content %}
    <h1 style="text-align: center">Оплата прошла успешно! Мы скоро с Вами свяжемся.</h1>
{% endblock content %}

src/pay/templates/pay/yandex_redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Redirect</title>
</head>
<body>

<!-- Платежная форма
     Эти поля обязательные, их нельзя удалять. -->
    <form action="https://money.yandex.ru/eshop.xml" method="post">
    <input name="shopId" value="620973" type="hidden" required/>
    <input name="scid" value="1205910" type="hidden" required/>
    <input name="shopSuccessURL" value="http://широкоформатная-печать.москва{% url "pay:success" token=success_token %}" type="hidden" required/>
    <input name="shopFailURL" value="http://широкоформатная-печать.москва{% url "pay:error" %}" type="hidden" required/>
    <input name="shopDefaultUrl" value="http://широкоформатная-печать.москва{% url "main:basic" %}" type="hidden" required/>
    <input name="sum" value="{{ sum }}" type="hidden" required><br><br>

<!-- Поле name="customerNumber" обязательное, его нельзя удалять.
     По нему вы сможете понять, кто вам заплатил.
     Вы можете назвать это поле как угодно. Например, вместо "Имя покупателя" написать
     "Идентификатор плательщика", "Номер клиента", "Имя клиента" или "Номер заказа". -->
     <input type="hidden" required name="customerNumber" value="{{ order_id }}"/><br><br>

<!-- Эти поля можно убрать или переименовать.
     Например, вместо "Телефон покупателя" написать "Цвет глаз" или "Номер автомобиля".  -->

<!-- Кнопку "Заплатить" можно назвать как угодно.
     Например, "Оплатить подписку" или "Внести деньги"-->
     <input style="display: none" id="submit" type="submit" value="Заплатить">
     </form>
<script>
    document.getElementById("submit").click()
</script>

</body>
</html>