src/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.basic, name='basic'),
    path('calculate_price/', views.calculate_price, name='calculate_price'),
    path('add_order_element/', views.add_order_element, name='add_order_element'),
    path('add_book_element/', views.add_book_element, name='add_book_element'),
    # path('submit_form/', views.submit_form, name='submit_form'),
    path('submit_head_form/', views.submit_head_form, name='submit_head_form'),
    path('verify_upload_file/', views.verify_upload_file, name='verify_upload_file'),

]

src/pay/urls.py
from django.urls import path
from . import views

app_name = 'pay'
urlpatterns = [
    path('yandex_redirect/<int:head_orders_id>/', views.yandex_redirect, name='yandex_redirect'),
    path('error/', views.PayError.as_view(), name='error'),
    path('success/<slug:token>/', views.pay_success, name='success'),

]

src/single_pages/urls.py
# coding=utf-8
from django.urls import path
from . import views


app_name = 'single_pages'

urlpatterns = [
    path("order_requirements/", views.Requirements.as_view(), name="order_requirements"),
]

src/users_app/urls.py
from django.urls import path
from . import views

app_name = 'users_app'
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.sign_up, name='signup'),
    path('activate/<str:uuid>/', views.activate, name='activate'),
    path('unsubscribe/<str:token>/', views.unsubscribe, name='unsubscribe'),

]

src/wideprint_moscow/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name='base/robots.txt',content_type='text/plain')),
    path('sitemap.xml', TemplateView.as_view(template_name='base/sitemap.xml',content_type='application/xml')),
    path('admin/', admin.site.urls),
    path('auth/', include('users_app.urls', namespace='authorization')),
    path('test_auth/', include('auth_.urls', namespace='test_authorization')),
    path('', include('main.urls', namespace='main')),
    path('order_status/', include('order_status.urls', namespace='order_status')),
    path('pay/', include('pay.urls', namespace='pay')),
    path('', include('single_pages.urls', namespace='single_pages')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>

<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock title %}</title>
  <meta name="keywords" content="{% block keywords %}{% endblock keywords %}">
  <meta name="description" content="{% block description %}{% endblock description %}">
  <meta name="fragment" content="!">

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="{% static 'base/css/all.css' %}">
  <link rel="stylesheet" href="{% static 'base/css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'base/css/base_style.css' %}">
  {% block style %}

  {% endblock style %}
  <script src="{% static 'base/js/jquery.js' %}"></script>
  <script src="{% static 'base/js/base.js' %}"></script>
  {% block script %}

  {% endblock script %}

  <link rel="shortcut icon" href="{% static 'base/img/favicon.png' %}" type="image/png">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="HandheldFriendly" content="true">
  <meta name="yandex-verification" content="4c251a0b67e8a6cc" />
</head>

<body>
  {% block head %}
  <header>
    <div class="top-header">
      <div class="container">
        <div class="" id="bars">
          <p class="bars"><i class="fas fa-bars"></i></p>
        </div>
        <nav class="menu-collapse menu-bars">
        <a href="https://вакуумная-формовка.москва">вакуумная-формовка.москва</a>
        <a href="https://3d-plakat.ru">3D плакаты</a>
          <a href="{% url 'single_pages:order_requirements' %}">Требования к макетам</a>
          <a href="{% url 'order_status:main' %}">Статус заказа</a>
          {% if user.is_authenticated %}
          <!-- <p>Добро пожаловать {{ user.get_full_name }}</p> -->
          <a href="{% url 'users_app:logout' %}">Выход</a>
          {% else %}
          <a href="{% url 'users_app:login' %}">Войти</a>
          {% endif %}

        </nav>
      </div>
    </div>
    <div class="bot-header">
      <div class="container">
        <a href="{% url 'main:basic' %}">
          <img src="{% static 'main/img/logo.png' %}" alt="logo">
        </a>
        <h1>Широкоформатная печать.москва</h1>
      </div>
    </div>
  </header>
  {% endblock head %}

  {{ yandex_counter|safe }}
  {% block content %}
  {% endblock content %}
</body>