src/order_status/urls.py
# coding=utf-8
from django.urls import path
from . import views


app_name = 'order_status'
urlpatterns = [
    path("", views.OrderStatus.as_view(), name='main'),
]

src/pay/urls.py
from django.urls import path
from . import views

app_name = 'pay'
urlpatterns = [
    path('yandex_redirect/<int:head_orders_id>/', views.yandex_redirect, name='yandex_redirect'),
    path('error/', views.PayError.as_view(), name='error'),
    path('success/<slug:token>/', views.pay_success, name='success'),

]

src/wideprint_moscow/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name='base/robots.txt',content_type='text/plain')),
    path('sitemap.xml', TemplateView.as_view(template_name='base/sitemap.xml',content_type='application/xml')),
    path('admin/', admin.site.urls),
    path('auth/', include('users_app.urls', namespace='authorization')),
    path('test_auth/', include('auth_.urls', namespace='test_authorization')),
    path('', include('main.urls', namespace='main')),
    path('order_status/', include('order_status.urls', namespace='order_status')),
    path('pay/', include('pay.urls', namespace='pay')),
    path('', include('single_pages.urls', namespace='single_pages')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/models.py
from django.contrib.auth.models import User
from django.db import models
from jsonfield import JSONField
from django.core.mail import send_mail
import secrets
import os
import random
import string


def randomString(stringLength=32):
    """Generate a random string of fixed length """
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(stringLength))

class YandexGoogleCounters(models.Model):
    class Meta:
        verbose_name_plural = 'statistic counters'
    yandex_counter = models.CharField(max_length=1000)
    google_counter = models.CharField(max_length=1000)

TYPE_OF_CARD = (
('Banner', 'Баннер'), # Первое значение для БД, второе выводится на дисплей
('Vinyl', 'Пленка'),
('PVC', 'Печать на пластике')
)

class Products(models.Model):
    class Meta:
        verbose_name_plural = 'products'
    product_type = models.CharField(max_length=50, choices=TYPE_OF_CARD)

class BannerPriceProduct(models.Model):
    class Meta:
        verbose_name_plural = 'products price'
    print_prices = JSONField()
    rings = models.FloatField(max_length=10,blank=True, null=True)
    edges = models.FloatField(max_length=10,blank=True, null=True)
    option_3_pocket = models.FloatField(max_length=10,blank=True, null=True)
    option_4_cord = models.FloatField(max_length=10,blank=True, null=True)

    def __str__(self):
        return str('Banner')

## class Clients(models.Model):
#     class Meta:
#         verbose_name_plural = 'clients'

ORDER_STATUS = (
('pending', 'В ожидании'), # Первое значение для БД, второе выводится на дисплей
('printing', 'В печати'),
('complete', 'Готово')
)

HEAD_ORDER_STATUS = (
('no_pay', 'Заказ не оплачен'),
('not_ready', 'Заказ не готов'),
('ready', 'Заказ готов'), # Первое значение для БД, второе выводится на дисплей
)

PRODUCT_TYPE = (
('banner_440', 'Баннер ламинированный 440 гр./кв.м'), # Первое значение для БД, второе выводится на дисплей
('banner_500', 'Баннер ламинированный 500 гр./кв.м'),
('banner_510', 'Баннер литой 510 гр./кв.м.'),
('vinyl_orajet', 'Самоклющаяся пленка ORAJET, белая'),
('vinyl_china', 'Самоклющаяся пленка Китай, белая'),
('pvc_1', 'ПВХ 1 мм'),
('pvc_2', 'ПВХ 2 мм'),
('pvc_4', 'ПВХ 4 мм'),
('pvc_5', 'ПВХ 5 мм'),
('pvc_10', 'ПВХ 10 мм'),
)

class HeadOrders(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        verbose_name='Заказчик'
    )
    delivery = models.BooleanField(default=False)
    address = models.CharField(max_length=50, blank=True, null=True)
    comments = models.CharField(max_length=50, blank=True, null=True)
    total_price_of_orders = models.IntegerField(default=0)
    status = models.CharField(max_length=50, choices=HEAD_ORDER_STATUS, default=1)
    success_token = models.CharField(
        default=randomString,
        max_length=255
    )


    def save(self, *args, **kwargs):
        email = self.user.email
        self.total_price_of_orders = 1
        if self.status == 'ready':
            send_mail(
                'Ваш заказ готов!',
                'Ваш заказ готов!',
                'wideprintmoscow@yandex.ru',
                [email],
                fail_silently=False,
            )
        super().save(*args, **kwargs)

    def __str__(self):
        try:
            return self.user.username
        except BaseException:
            return str(self.id)

    class Meta:
        verbose_name_plural = 'HeadOrders'

class Orders(models.Model):
    product_type = models.CharField(max_length=50, choices=PRODUCT_TYPE)
    quantity = models.IntegerField(default=0)
    edges = models.BooleanField(default=False)
    rings = models.BooleanField(default=False)
    cord = models.BooleanField(default=False)
    pocket = models.BooleanField(default=False)
    dpi = models.CharField(max_length=10)
    design = models.BooleanField()
    description = models.CharField(max_length=500, blank=True, null=True)
    size_v = models.CharField(max_length=50, default=100) # remove blank and null in production
    size_h = models.CharField(max_length=50, default=100)
    file = models.FileField(
        max_length=255,
        default=None,
        blank=True,
        null=True,
        upload_to='orders/%Y/%m/%d',
    ) # MEDIA_ROOT/documents/
    total_price = models.DecimalField(default=0, max_digits=30, decimal_places=2)
    status = models.CharField(max_length=50, choices=ORDER_STATUS, default='pending')
    source = models.ForeignKey(HeadOrders, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return str(self.source)

    def save(self, *args, **kwargs):
        try:
            this_entry = Orders.objects.get(id=self.id)
            if this_entry.file != self.file:
                this_entry.file.delete(save=False)
        except:
            pass
        return super(Orders, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.file.delete(save=False)
        return super(Orders, self).delete(*args, **kwargs)

    def filename(self):
        return os.path.basename(self.file.name)

    class Meta:
        verbose_name_plural = 'Orders'

src/order_status/models.py
from django.db import models

# Create your models here.

src/order_status/views.py
from django.views.generic import View
from django.shortcuts import render
from main.models import Orders, HeadOrders


# Create your views here.


class OrderStatus(View):
    """Отображает страницу статуса заказа"""

    def get(self, request):
        if request.user.is_authenticated:
            user_orders = Orders.objects.filter(source__user__username=request.user.username)
            active_orders = user_orders.filter(status='pending')
            pending_orders = user_orders.filter(status='complete')
            total_price = 0
            for i in user_orders:
                total_price += i.total_price

            percent = (total_price / 440461) * 100
            if percent > 100:
                percent = 100
            print(total_price, percent)
            return render(request, 'order_status/status.html', {"active": active_orders,
                                                                "archive": pending_orders,
                                                                'percent': percent,
                                                                'total_price': total_price})
        else:
            return render(request, 'order_status/status.html')

src/order_status/templates/order_status/status.html
{% extends 'base/base.html' %}
    {% load staticfiles %}
    {% load mathfilters %}
{% load filename %}
    {% block title %}Статус заказа{% endblock title %}
    {% block style %}

    <link rel="stylesheet" type="text/css" href="{% static 'order_status/css/status.css' %}">

    <style>
        .progress-main__bar::before {
            width: {{ percent }}%;
        }

        .progress-main__current-sum {
            left: {{ percent }}%;

        }

    </style>
{% endblock %}

{% block content %}
<main>

    {% if user.is_authenticated %}
    <div class="status">
        <h2 class="status__main-header">Совершайте заказы и получайте накопительную скидку на заказы от суммы
            совершенных заказов за последний год.</h2>
        <div class="status__progress">
            <h3><span>Ваш прогресс:</span><br>Итого заказано за год на сумму 28000 ₽</h3>
            <div class="progress-wrap">
            <div class="progress-main">
                <div class="progress-main__tips">
                    <div class="tips__sale sale-3">
                        <p>скидка <span>3%</span></p>
                        <p>30.000 &#8381;</p>
                    </div>
                    <div class="tips__sale sale-7">
                        <p>скидка <span>7%</span></p>
                        <p>100.000 &#8381;</p>
                    </div>
                    <div class="tips__sale sale-13">
                        <p>скидка <span>13%</span></p>
                        <p>300.000 &#8381;</p>
                    </div>
                </div>
                <div class="progress-main__bar"></div>

                <p class="progress-main__current-sum"><span> {{ total_price }} <b>&#8381;</b></span></p>
            </div>
                </div>
        </div>
        <div class="status__order-container">
            <h3 class="order__main-header">Текущие заказы</h3>
            <div class="order__scroll-wrap">
            <div class="status__order-wrap">

                <table class="status__order">
                    <tbody>
                    {% if active %}
                    <tr>
                        <td class="order__cell order__num">ЗАКАЗ № <span>{{ active.0.id }}</span></td>
                        <td class="order__cell order__file-name column-name">Назввание макета:</td>
                        <td class="order__cell order__value column-name">Количество:</td>
                        <td class="order__cell order__cost column-name">Стоимость:</td>
                        <td class="order__cell order__repeat"></td>
                    </tr>
                    <tr>
                        <td class="order__cell order__full-name">{{ active.0.get_product_type_display }}, {{ active.0.size_v }}x{{ active.0.size_h }} см</td>
                        <td class="order__cell order__file-name">{% if active.0.file %}{{ active.0.file | getfilename }}{% endif %}</td>
                        <td class="order__cell order__value">{{ active.0.quantity }} шт</td>
                        <td class="order__cell order__cost"><span>{{ active.0.total_price }} <b>&#8381;</b></span></td>
                        <td class="order__cell order__repeat"></td>
                    </tr>
                        {% else %}
                        <tr>
                        <td class="order__cell order__num">ЗАКАЗ № <span></span></td>
                        <td class="order__cell order__file-name column-name">Назввание макета:</td>
                        <td class="order__cell order__value column-name">Количество:</td>
                        <td class="order__cell order__cost column-name">Стоимость:</td>
                        <td class="order__cell order__repeat"></td>
                    </tr>
                        {% endif %}
                    {% for order in active|slice:"1:" %}
                        <tr>
                        <td class="order__cell order__num">ЗАКАЗ № <span>{{ order.id }}</span></td>
                        <td class="order__cell order__file-name column-name">Назввание макета:</td>
                        <td class="order__cell order__value column-name">Количество:</td>
                        <td class="order__cell order__cost column-name">Стоимость:</td>
                        <td class="order__cell order__repeat"></td>
                    </tr>
                    <tr>
                        <td class="order__cell order__full-name">{{ order.get_product_type_display }}, {{ order.size_v }}x{{ order.size_h }} см</td>
                        <td class="order__cell order__file-name">{% if order.file %}{{ order.file | getfilename }}{% endif %}</td>
                        <td class="order__cell order__value">{{ order.quantity }} шт</td>
                        <td class="order__cell order__cost"><span>{{ order.total_price }} <b>&#8381;</b></span></td>
                        <td class="order__cell order__repeat"></td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
                </div>


        </div>


        <div class="status__order-container archive">
            <h3 class="order__main-header">Архивные заказы</h3>
            <div class="order__scroll-wrap">
            <div class="status__order-wrap">

                <table class="status__order">
                    <tbody>
                    {% if archive %}
                    <tr>
                        <td class="order__cell order__num">ЗАКАЗ № <span>{{ archive.0.id }}</span></td>
                        <td class="order__cell order__file-name column-name">Назввание макета:</td>
                        <td class="order__cell order__value column-name">Количество:</td>
                        <td class="order__cell order__cost column-name">Стоимость:</td>
                        <td class="order__cell order__repeat"></td>
                    </tr>
                    <tr>
                       <td class="order__cell order__full-name">{{ archive.0.get_product_type_display }}, {{ archive.0.size_v }}x{{ archive.0.size_h }} см</td>
                        <td class="order__cell order__file-name">{% if archive.0.file %}{{ archive.0.file | getfilename }}{% endif %}</td>
                        <td class="order__cell order__value">{{ archive.0.quantity }} шт</td>
                        <td class="order__cell order__cost"><span>{{ archive.0.total_price }} <b>&#8381;</b></span></td>
                        <td class="order__cell order__repeat"><div class="cell__repeat-btn"><p>Повторить</p></div></td>
                    </tr>
                        {% else %}
                        <tr>
                        <td class="order__cell order__num">ЗАКАЗ № <span></span></td>
                        <td class="order__cell order__file-name column-name">Назввание макета:</td>
                        <td class="order__cell order__value column-name">Количество:</td>
                        <td class="order__cell order__cost column-name">Стоимость:</td>
                        <td class="order__cell order__repeat"></td>
                    </tr>
                    {% endif %}

                    {% for order in archive|slice:"1:" %}
                    <tr>
                        <td class="order__cell order__num">ЗАКАЗ № <span>{{ order.id }}</span></td>
                        <td class="order__cell order__file-name column-name">Назввание макета:</td>
                        <td class="order__cell order__value column-name">Количество:</td>
                        <td class="order__cell order__cost column-name">Стоимость:</td>
                        <td class="order__cell order__repeat"></td>
                    </tr>
                    <tr>
                        <td class="order__cell order__full-name">{{ order.get_product_type_display }}, {{ order.size_v }}x{{ order.size_h }} см</td>
                        <td class="order__cell order__file-name">{% if order.file %}{{ order.file | getfilename }}{% endif %}</td>
                        <td class="order__cell order__value">{{ order.quantity }} шт</td>
                        <td class="order__cell order__cost"><span>{{ order.total_price }} <b>&#8381;</b></span></td>
                        <td class="order__cell order__repeat"><div class="cell__repeat-btn"><p>Повторить</p></div></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            </div>


        </div>
    </div>
{% else %}

        <p class="auth-msg">Авторизуйтесь</p>

{% endif %}
</main>

{% endblock content %}